### ISSUE TITLE
Doesn't display properly in firefox

### ISSUE THREAD

**Issue by drossy** [stfc/Cablebox#1]
The pdu tables should flow horizontally for the same rack, but this is not working in Firefox (it does display as intended in Chrome)

**Comment by jrha** [comment]
If I add the following to `table.pdu` it looks right in firefox:
```css
table.pdu {
    …
    float: left;
    width: auto;
}
```
